# Generated by Django 3.0.6 on 2020-06-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_dislike_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='users',
        ),
        migrations.DeleteModel(
            name='DisLike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
